const localStorageState = {
	helpers: {
		101_001: {
			// Iron Chunk
			category: 'BUILDING',
			tierOne: 1,
			tierOneLock: true,
			tierTwo: 0,
			tierTwoLock: false,
			tierThree: 0,
			tierThreeLock: false,
			tierFour: 0,
			tierOneGoal: '',
			tierTwoGoal: '',
			tierThreeGoal: '',
			tierFourGoal: '',
		},
		101_301: {
			// Birch Wood
			category: 'WOOD',
			tierOne: 1,
			tierOneLock: true,
			tierTwo: 0,
			tierTwoLock: false,
			tierThree: 0,
			tierThreeLock: false,
			tierFour: 0,
			tierOneGoal: '',
			tierTwoGoal: '',
			tierThreeGoal: '',
			tierFourGoal: '',
		},
		104_104: {
			// Brilliant Diamond Gemstone
			category: 'ASCENSION',
			tierOne: 1,
			tierOneLock: false,
			tierTwo: 2,
			tierTwoLock: false,
			tierThree: 3,
			tierThreeLock: true,
			tierFour: 4,
			tierOneGoal: '',
			tierTwoGoal: '',
			tierThreeGoal: 2,
			tierFourGoal: '',
		},
		104_303: {
			// Philosophies of Freedom
			category: 'TALENT',
			tierOne: 1,
			tierOneLock: false,
			tierTwo: 2,
			tierTwoLock: false,
			tierThree: 3,
			tierThreeLock: false,
			tierFour: 0,
			tierOneGoal: '',
			tierTwoGoal: 2,
			tierThreeGoal: '',
			tierFourGoal: '',
		},
		112_004: {
			// Slime Concentrate
			category: 'ENHANCEMENT',
			tierOne: 1,
			tierOneLock: false,
			tierTwo: 2,
			tierTwoLock: false,
			tierThree: 3,
			tierThreeLock: false,
			tierFour: 0,
			tierOneGoal: 1,
			tierTwoGoal: '',
			tierThreeGoal: '',
			tierFourGoal: '',
		},
		113_001: {
			// Hurricane Seed'
			category: 'LEVEL',
			tierOne: 1,
			tierOneLock: true,
			tierTwo: 0,
			tierTwoLock: false,
			tierThree: 0,
			tierThreeLock: false,
			tierFour: 0,
			tierOneGoal: '',
			tierTwoGoal: '',
			tierThreeGoal: '',
			tierFourGoal: '',
		},
		114_004: {
			// Scattered Piece of Decarabian's Dream
			category: 'WEAPON',
			tierOne: 1,
			tierOneLock: false,
			tierTwo: 2,
			tierTwoLock: false,
			tierThree: 3,
			tierThreeLock: true,
			tierFour: 4,
			tierOneGoal: '',
			tierTwoGoal: '',
			tierThreeGoal: 3,
			tierFourGoal: 5,
		},
		131_000: {
			// Medaka
			category: 'FISH',
			tierOne: 1,
			tierOneLock: true,
			tierTwo: 0,
			tierTwoLock: false,
			tierThree: 0,
			tierThreeLock: false,
			tierFour: 0,
			tierOneGoal: '',
			tierTwoGoal: '',
			tierThreeGoal: '',
			tierFourGoal: '',
		},
	},
};

export default localStorageState;
