name: "Console"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions: write-all

jobs:
  console:
    runs-on: ubuntu-latest
    name: Get console logs
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Make sure it builds. Then show a preview.
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Exit if build did not succeed
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        run: exit 1
        shell: bash
      - name: Sleep for 120 seconds
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: sleep 120s
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use WebApp Console Log Action
        uses: Primajin/webapp-console-log-action@7a95eb3b47815095e72d8977fedf7cfd6867e967
        with:
          webapp-url: https://helper.farm/pr-preview/pr-${{ github.event.number }}/
          regexp-error: 'Failed \D+ 404 \(\)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
